### ISSUE TITLE
`GLIBCXX_3.4.29' not found 

### ISSUE THREAD

**Issue by dfguerrerom** [sepal-contrib/gwb#74]
There's something wrong with the installation of GWB... SEPAL does it with https://github.com/openforis/sepal/blob/master/modules/geospatial-toolkit/script/init_gwb.sh as it is recommended in https://forest.jrc.ec.europa.eu/en/activities/lpa/gwb/... however, the following error happens after running the tool either by CLI or the GUI

```python
/opt/GWB/tools/idl/bin/bin.linux.x86_64/idl: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/GWB/tools/idl/bin/bin.linux.x86_64/libidl.so)

/opt/GWB/tools/idl/bin/bin.linux.x86_64/idl: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/GWB/tools/idl/bin/bin.linux.x86_64/libalan.so)
```

The issue can be related to the sepal Ubuntu version which is required by the latest version of GWB...

**Comment by vogtpet** [comment]
Hi Daniel,
which version of GWB is installed? See /opt/GWB/tools/GWB_version.txt
Most likely not the recent version 1.9.3, which can be easily installed by running as root: `/opt/GWB/tools/GWBupdate_deb.sh`
This is just a shell-script to facilitate keeping GWB uptodate. Can you try this and report back? 
Thanks!

**Comment by dfguerrerom** [comment]
Isn't there a way to pin to an specific version? It would be easier and safer to not automatically upgrade the `gwb` package until we have ready the UI, otherwise, we'll end with errors that were not expected.

**Comment by vogtpet** [comment]
The directory [packages](https://github.com/ec-jrc/GWB/tree/main/packages) now has all versions. There is no way or need to pin a specific version because `GWB` is not in the official Debian repo. You will only get the note that an older version is outdated, that's all. To use any version, simply download it from the above location, then use the `apt` command to uninstall the currently installed version and then install the deb-package of your choice. 
And to automatically have the current version installed, place the script `/opt/GWB/tools/GWBupdate_deb.sh` in a cron job.
Does this help?

**Comment by dfguerrerom** [comment]
I'm sorry, I didn't mean to say pin, but "point" to a specific version, Thanks for sharing the package version folder, we might use it to downgrade the currently installed version until we upgrade our Ubuntu version.

**Comment by vogtpet** [comment]
On buntu 20.04 LTS (SEPAL) the most uptodate GWB version that should work is version 1.9.1. GWB version 1.9.2 and up uses the uptodate IDL framework, which works fine on buntu 22.04 LTS.

**Comment by dfguerrerom** [comment]
This has been solved on our test server. We are now using latest version, as soon as we release the changes it will be fully available.
